// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7TB18U9TubUh2qWJ__PXp7sQcQXx_WY8',
    appId: '1:911434825963:web:63ef21dc1ea7451fa9feae',
    messagingSenderId: '911434825963',
    projectId: 'my-clean-app-2e59e',
    authDomain: 'my-clean-app-2e59e.firebaseapp.com',
    storageBucket: 'my-clean-app-2e59e.firebasestorage.app',
    measurementId: 'G-2WWG7JZ09E',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAbjTmkNrmJVE1FgRGXOXow99uRNf1QWQ',
    appId: '1:911434825963:ios:c61142a834860f52a9feae',
    messagingSenderId: '911434825963',
    projectId: 'my-clean-app-2e59e',
    storageBucket: 'my-clean-app-2e59e.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAbjTmkNrmJVE1FgRGXOXow99uRNf1QWQ',
    appId: '1:911434825963:ios:c61142a834860f52a9feae',
    messagingSenderId: '911434825963',
    projectId: 'my-clean-app-2e59e',
    storageBucket: 'my-clean-app-2e59e.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7TB18U9TubUh2qWJ__PXp7sQcQXx_WY8',
    appId: '1:911434825963:web:f0ca6a44728b4986a9feae',
    messagingSenderId: '911434825963',
    projectId: 'my-clean-app-2e59e',
    authDomain: 'my-clean-app-2e59e.firebaseapp.com',
    storageBucket: 'my-clean-app-2e59e.firebasestorage.app',
    measurementId: 'G-7QD0Y4Q1Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3xZZ7Y4I6H5iH_SS1OYlBFdWCwBPJQKM',
    appId: '1:911434825963:android:582b4bf9b659ed17a9feae',
    messagingSenderId: '911434825963',
    projectId: 'my-clean-app-2e59e',
    storageBucket: 'my-clean-app-2e59e.firebasestorage.app',
  );

}